CLASS ltc_main DEFINITION FINAL
  FOR TESTING RISK LEVEL HARMLESS DURATION SHORT.

  PRIVATE SECTION.
    METHODS build_file_path FOR TESTING RAISING cx_static_check.
ENDCLASS.


CLASS ltc_main IMPLEMENTATION.
  METHOD build_file_path ##NEEDED.
  ENDMETHOD.
ENDCLASS.
